services:
  serving:
    build:
      context: ./
      dockerfile: Dockerfile.serving
    image: nhl-goal-prediction/serving:latest
    ports:
      - 5000:5000
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}

  streamlit:
    build:
      context: ./
      dockerfile: Dockerfile.streamlit
    image: nhl-goal-prediction/streamlit:latest
    ports:
      - "8501:8501"
    environment:
      - SERVING_IP=serving  # Adresse IP interne du conteneur Flask
      - WANDB_API_KEY=${WANDB_API_KEY}
    depends_on:
      - serving   # S'assurer que Flask d√©marre avant Streamlit (sinon erreur)
      

     
